- defaults:
    link:
      force: true

- clean: ['~']

- link:
    ~/.bash_profile: scripts/bash_profile.bash
    ~/.bash_logout: scripts/bash_logout.bash
    ~/.nanorc: configs/nanorc
    ~/.config/liquidpromptrc: configs/liquidpromptrc
    ~/.dircolors: modules/.dircolors/dircolors.256dark

- shell:
    - [git submodule update --init --depth 1, Initiating submodules...]
