- defaults:
    link:
      force: true

- clean: ['~']

- link:
    ~/.bash_profile: bash_profile.bash
    ~/.bash_logout: bash_logout.bash
    ~/.nanorc: configs/nanorc

- shell:
    - [git submodule update --init --depth 10, Initiating submodules...]
