- defaults:
    link:
      force: true

- clean: ['~']

- link:
    ~/.bash_profile: bash_profile.bash
    ~/.bash_logout: bash_logout.bash
    ~/.nanorc: configs/nanorc
    ~/.todo/config:
      create: true
      path: configs/todo.cfg

- shell:
    - [git submodule update --init --depth 1, Initiating submodules...]

- link:
    ~/.dotfiles/.bash-it/custom/themes:
      create: true
      path: themes/bash-it-themes
