add_newline = false
format      = "$all"

[aws]
symbol = " "

[battery]
full_symbol        = ""
charging_symbol    = ""
discharging_symbol = ""
format             = "[$symbol$percentage]($style) "
[[battery.display]]
style              = "bold red"
threshold          = 15
[[battery.display]]
style              = "bold yellow"
threshold          = 30

[character]
error_symbol   = "[❯](bold red)"   # "➜" "▶"
success_symbol = "[❯](bold green)" # "➜" "▶"
vicmd_symbol   = "[❮](bold green)"

[cmake]
disabled = true

[cmd_duration]
min_time = 5000

[conda]
disabled = true
symbol = " "

[crystal]
disabled = true

[dart]
disabled = true
symbol   = " "

[directory]
format = "[$read_only](red)[$path](bold cyan) "
read_only_symbol = " "
truncation_symbol = "…/"

[docker_context]
symbol = " "

[dotnet]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol   = " "

[elm]
disabled = true
symbol   = " "

[erlang]
disabled = true
symbol = " "

[gcloud]
symbol = " "

[git_branch]
format = "[( $branch )](bold bright-purple)"

[git_commit]
format             = "[( $hash )](bold blue)"
commit_hash_length = 8

[git_state]
format      = "[($state\\($progress_current/$progress_total\\) )](bold red)"

[git_status]
format     = "[(\\[$all_status$ahead_behind\\] )](bold yellow)"
conflicted = "=${count}"
ahead      = "⇡${count}"
behind     = "⇣${count}"
diverged   = "⇕⇡${ahead_count}⇣${behind_count}"
untracked  = "?${count}"
stashed    = "≡${count}"
modified   = "!${count}"
staged     = "+${count}"
renamed    = "»${count}"
deleted    = "✘${count}"

[golang]
symbol = " "

[haskell]
disabled = true
symbol   = " "

[helm]
disabled = true
symbol   = "⎈ "

[hg_branch]
disabled = true
symbol   = " "

[hostname]
trim_at = ""

[java]
disabled = true
symbol   = " "

[jobs]
symbol = " "

[julia]
disabled = true
symbol   = " "

[kubernetes]
disabled = true
symbol   = "☸ "

[memory_usage]
symbol = " "

[nim]
disabled = true
symbol   = " "

[nix_shell]
disabled = true
symbol   = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
disabled = false
symbol   = " "

[php]
disabled = true
symbol   = " "

[purescript]
disabled = true

[python]
symbol = " "

[ocaml]
disabled = true
symbol   = "🐫 "

[ruby]
symbol = " "

[rust]
symbol = " "

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = false
format   = "[${status}](bold red) "

[swift]
disabled = true
symbol   = " "

[terraform]
disabled = true
symbol   = "💠 "

[time]
disabled = true

[user]
disabled = false

[zig]
disabled = true
symbol   = "⚡️ "
