add_newline = false

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
[battery.display]
style = "bold red"
threshold = 20

[character]
symbol = "❯" # "➜" "▶"
vicmd_symbol = "❮"

[cmd_duration]
min_time = 5000

[conda]
disabled = true
symbol = " "

[crystal]
disabled = true

[docker]
symbol = " "

[dotnet]
disabled = true

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[erlang]
disabled = true

[git_branch]
style = "bold 164"
symbol = " "

[git_status]
show_sync_count = true
prefix = "("
suffix = ") "
style = "bold yellow"
stashed = "≡"
[git_status.conflicted_count]
enabled = true
[git_status.untracked_count]
enabled = true
[git_status.stashed_count]
enabled = true
[git_status.modified_count]
enabled = true
[git_status.staged_count]
enabled = true
[git_status.renamed_count]
enabled = true
[git_status.deleted_count]
enabled = true

[golang]
symbol = " "

[haskell]
disabled = true
symbol = " "

[hg_branch]
symbol = " "

[java]
disabled = true
symbol = " "

[jobs]
symbol = "✦ "

[julia]
disabled = true
symbol = " "

[kubernetes]
disabled = true

[memory_usage]
symbol = " "

[nim]
disabled = true
symbol = " "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
disabled = true
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[singularity]
disabled = true

[terraform]
disabled = true
