add_newline = false

[battery.display]
threshold = 20
style = "bold red"

[character]
symbol = "❯" # "➜" "▶"
vicmd_symbol = "❮"

[cmd_duration]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[git_branch]
style = "bold 164"

[git_status]
show_sync_count = true
prefix = "("
suffix = ") "
style = "bold yellow"
stashed = "≡"
[git_status.conflicted_count]
enabled = true
[git_status.untracked_count]
enabled = true
[git_status.stashed_count]
enabled = true
[git_status.modified_count]
enabled = true
[git_status.staged_count]
enabled = true
[git_status.renamed_count]
enabled = true
[git_status.deleted_count]
enabled = true

[haskell]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[nix_shell]
disabled = true

[php]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true
